package br.com.ifba.biblioteca.editora.view;

import org.springframework.stereotype.Component;
import br.com.ifba.biblioteca.editora.controller.EditoraIController;
import org.springframework.beans.factory.annotation.Autowired;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import br.com.ifba.biblioteca.editora.entity.Editora;
import javax.swing.JOptionPane;

/**
 *
 * @author misae
 */

//tela responsável pela listagem e gerenciamento de Editoras
@Component
public class EditoraListar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditoraListar.class.getName());
    
    //controller responsável pelas operações relacionadas à Editora
    private final EditoraIController controller;

    /**
     * Creates new form EditoraListar
     */
    
    //inicializa a tela de listagem de editoras, configurando ações, layout e carregando editoras ativas.
    public EditoraListar(EditoraIController controller) {
        this.controller = controller;
        initComponents();
        configurarAcoes();
        configurarTela();
        carregarTabela(controller.listarAtivas());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEditoras = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnInativar = new javax.swing.JButton();
        btnAtualizarTabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEditoras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CNPJ", "Telefone", "Endereço", "Situação"
            }
        ));
        jScrollPane1.setViewportView(tblEditoras);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("EDITORAS");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setText("Nome:");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setText("Editar");

        btnInativar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInativar.setText("Inativar");

        btnAtualizarTabela.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtualizarTabela.setText("Atualizar");
        btnAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFiltrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdicionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizarTabela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnInativar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1171, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNome)))
                        .addGap(23, 23, 23))))
            .addGroup(layout.createSequentialGroup()
                .addGap(513, 513, 513)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnEditar)
                    .addComponent(btnInativar)
                    .addComponent(btnAtualizarTabela))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //método que configura propriedades visuais da tela
    private void configurarTela() {
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

         //oculta a coluna de ID da tabela
        tblEditoras.getColumnModel().getColumn(0).setMinWidth(0);
        tblEditoras.getColumnModel().getColumn(0).setMaxWidth(0);
    }
    
    private void configurarAcoes() {
        btnAdicionar.addActionListener(e -> abrirTelaAdicionar());
        btnFiltrar.addActionListener(e -> filtrarEditoras());
        btnInativar.addActionListener(e -> inativarEditora());
        btnEditar.addActionListener(e -> editarEditora());

    }
    
    //abre a tela de cadastro de Editora e recarrega a tabela ao fechar
    private void abrirTelaAdicionar() {
        EditoraAdicionar tela = new EditoraAdicionar(controller);
        tela.setLocationRelativeTo(this);
        tela.setVisible(true);

        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                carregarTabela(controller.listarAtivas());
            }
        });
    }
    
    //abre a tela de edição da editora selecionada
    private void editarEditora() {
        int linha = tblEditoras.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma editora para editar.");
            return;
        }

        Long id = (Long) tblEditoras.getValueAt(linha, 0);

        Editora editora = controller.findById(id);
        if (editora == null) {
            JOptionPane.showMessageDialog(this, "Editora não encontrada!");
            return;
        }

        EditoraEditar telaEditar = new EditoraEditar(controller, id);
        telaEditar.setLocationRelativeTo(this);
        telaEditar.setVisible(true);

        telaEditar.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                carregarTabela(controller.listarAtivas());
            }
        });
    }

    
    private void filtrarEditoras() {
        String nome = txtNome.getText();
    List<Editora> editoras = controller.filtrarPorNome(nome);

    DefaultTableModel model = (DefaultTableModel) tblEditoras.getModel();
    model.setRowCount(0);

    for (Editora e : editoras) {
        model.addRow(new Object[] {
            e.getId(),
            e.getNome(),
            e.getCnpj(),
            e.getTelefone(),
            e.getEndereco(),
            e.getSituacao()
        });
    }
    
    }

    //metodo q inativa a editora selecionada após confirmação do usuário
    private void inativarEditora() {
        int linha = tblEditoras.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma editora para inativar.");
            return;
        }

        Long id = (Long) tblEditoras.getValueAt(linha, 0);

        int confirmar = JOptionPane.showConfirmDialog(this,
            "Deseja realmente inativar esta editora?", "Confirmação",
            JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            controller.inativar(id); // método do controller
            carregarTabela(controller.listarAtivas());
            JOptionPane.showMessageDialog(this, "Editora inativada com sucesso.");
        }
    }



    
    
    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        filtrarEditoras();
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarTabelaActionPerformed
        txtNome.setText(""); // limpa o campo de filtro
        carregarTabela(controller.listarAtivas()); // recarrega todas as editoras ativas
    }//GEN-LAST:event_btnAtualizarTabelaActionPerformed

    /**
     * @param args the command line arguments
     */
    
    //preenche a tabela com a lista de editoras informada
    private void carregarTabela(List<Editora> editoras) {

        DefaultTableModel model =
            (DefaultTableModel) tblEditoras.getModel();

        model.setRowCount(0); // limpa tabela

        for (Editora e : editoras) {
            model.addRow(new Object[]{
                e.getId(),
                e.getNome(),
                e.getCnpj(),
                e.getTelefone(),
                e.getEndereco(),
                e.getSituacao()
            });
        }

    // esconder coluna ID
    tblEditoras.getColumnModel().getColumn(0).setMinWidth(0);
    tblEditoras.getColumnModel().getColumn(0).setMaxWidth(0);
    
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizarTabela;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnInativar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JTable tblEditoras;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
