package br.com.ifba.biblioteca.cliente.view;

import br.com.ifba.biblioteca.cliente.controller.ClienteIController;
import br.com.ifba.biblioteca.cliente.entity.Cliente;
import br.com.ifba.biblioteca.cliente.entity.TipoCliente;
import br.com.ifba.biblioteca.pessoa.entity.StatusPessoa;
import javax.swing.JOptionPane;
import org.springframework.stereotype.Component;

/**
 *
 * @author misae
 */


public class ClienteAdicionar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteAdicionar.class.getName());

    /**
     * Creates new form ClienteAdicionar
     */
    

    // atributo para o controlador, que gerencia a lógica dos clientes
    private final ClienteIController controller;
    
    // Construtor para criar a tela em modo cadastro
    public ClienteAdicionar(ClienteIController controller) {
        this.controller = controller;
        initComponents();
        configurarTela();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNomeCompleto = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblTipoDeCliente = new javax.swing.JLabel();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        lblLimiteEmprestimos = new javax.swing.JLabel();
        txtLimiteEmprestimo = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADICIONAR CLIENTE");

        lblNomeCompleto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNomeCompleto.setText("Nome Completo:");

        lblCpf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCpf.setText("CPF:");

        lblTelefone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTelefone.setText("Telefone:");

        lblTipoDeCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoDeCliente.setText("Tipo de Cliente:");

        cmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALUNO", "PROFESSOR", "VISITANTE" }));
        cmbTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoClienteActionPerformed(evt);
            }
        });

        lblLimiteEmprestimos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLimiteEmprestimos.setText("Limite de Empréstimos:");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCpf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(lblTipoDeCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblLimiteEmprestimos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLimiteEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnSalvar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNomeCompleto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCompleto)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoDeCliente)
                    .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimiteEmprestimos)
                    .addComponent(txtLimiteEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void configurarTela() {
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null); // centraliza a tela
        
        atualizarLimiteEmprestimo();// define automaticamente o limite inicial conforme o tipo de cliente
    }
    
    private void preencherCampos(Cliente cliente) {
        txtNome.setText(cliente.getNomeCompleto());
        txtCPF.setText(cliente.getCpf());
        txtTelefone.setText(cliente.getTelefone());
        cmbTipoCliente.setSelectedItem(cliente.getTipoCliente().name());
        txtLimiteEmprestimo.setText(cliente.getLimiteEmprestimo().toString());
    }

    //atualiza automaticamente o limite de empréstimos de acordo com o tipo de cliente selecionado (ALUNO, PROFESSOR ou VISITANTE)
    private void atualizarLimiteEmprestimo() {

        String tipoSelecionado = (String) cmbTipoCliente.getSelectedItem();

        if (tipoSelecionado == null) {
            return;
        }

        TipoCliente tipo = TipoCliente.valueOf(tipoSelecionado);

        switch (tipo) {
            case ALUNO:
                txtLimiteEmprestimo.setText("3");
                break;

            case PROFESSOR:
                txtLimiteEmprestimo.setText("5");
                break;

            case VISITANTE:
                txtLimiteEmprestimo.setText("1");
                break;
        }

        // impede edição manual do limite, pois ele é definido pelo tipo de cliente
        txtLimiteEmprestimo.setEditable(false);
    }

    
    private void salvarCliente(){
        try{
            Cliente cliente = new Cliente();

        
            // Verificando se os campos obrigatórios estão preenchidos
            if (txtNome.getText().isEmpty()) {
                throw new RuntimeException("Nome Completo é obrigatório.");
            }
            if (txtCPF.getText().isEmpty()) {
                throw new RuntimeException("CPF é obrigatório.");
            }
            if (txtTelefone.getText().isEmpty()) {
                throw new RuntimeException("Telefone é obrigatório.");
            }
            
            // Verifique se o CPF já está cadastrado
            String cpf = txtCPF.getText();
            if (controller.verificarCpfExistente(cpf)) {
                JOptionPane.showMessageDialog(this, "CPF já cadastrado!", "Erro", JOptionPane.ERROR_MESSAGE);
                return;  // Não salva o cliente se o CPF já existir
            }
        
            // Obtendo dados dos campos
            cliente.setNomeCompleto(txtNome.getText());  // Nome Completo
            cliente.setCpf(txtCPF.getText());  // CPF
            cliente.setTelefone(txtTelefone.getText());  // Telefone
        
            // Verifique se o limite de empréstimos foi preenchido corretamente
            String limiteStr = txtLimiteEmprestimo.getText();
            if (limiteStr.isEmpty()) {
                throw new RuntimeException("Limite de Empréstimos é obrigatório");
            }
            
            try {
                cliente.setLimiteEmprestimo(Integer.parseInt(limiteStr));
            } catch (NumberFormatException ex) {
                throw new RuntimeException("Limite de empréstimos deve ser um número inteiro.");
            }
        
            // Tipo de Cliente, configurando com o JComboBox
            String tipoSelecionado = (String) cmbTipoCliente.getSelectedItem();

            if (tipoSelecionado == null) {
                throw new RuntimeException("Tipo de Cliente não selecionado");
            }
        

            TipoCliente tipoCliente = TipoCliente.valueOf(tipoSelecionado);
            cliente.setTipoCliente(tipoCliente);

        
            // Definindo o status do cliente como ATIVO
            cliente.setStatusPessoa(StatusPessoa.ATIVO);

            
            controller.save(cliente);
            

            JOptionPane.showMessageDialog(this,
                "Cliente cadastrado com sucesso!",
                "Sucesso",
                JOptionPane.INFORMATION_MESSAGE);

            this.dispose();  // Fecha a tela após salvar
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                e.getMessage(),
                "Erro",
                JOptionPane.ERROR_MESSAGE);
        }
            
        }
        
    
    //// atualiza automaticamente o limite quando o tipo de cliente é alterado
    private void cmbTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoClienteActionPerformed
        atualizarLimiteEmprestimo();
    }//GEN-LAST:event_cmbTipoClienteActionPerformed

    //aciona metodo de salvar cliente
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        salvarCliente();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Tem certeza que deseja cancelar?", "Confirmar Cancelamento", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblLimiteEmprestimos;
    private javax.swing.JLabel lblNomeCompleto;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTipoDeCliente;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtLimiteEmprestimo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
