package br.com.ifba.biblioteca.cliente.view;

import br.com.ifba.biblioteca.cliente.controller.ClienteIController;
import br.com.ifba.biblioteca.cliente.entity.Cliente;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import org.springframework.stereotype.Component;
import br.com.ifba.biblioteca.cliente.view.ClienteAdicionar;
import javax.swing.JOptionPane;


/**
 *
 * @author misae
 */

@Component
public class ClienteListar extends javax.swing.JFrame {
    
    
    // atributo para o controlador, que gerencia a lógica dos clientes
    private final ClienteIController controller;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteListar.class.getName());
    

    // Construtor da tela de listagem de clientes
    public ClienteListar(ClienteIController controller) {
        this.controller = controller;
        initComponents();
        configurarAcoes();// aqui configura os eventos dos botões
        carregarClientes();//carrega todos os clientes ao iniciar 
        configurarTela();  //aqui só pra ajustes na tela 
    }
    
    private void configurarTela() {
        setLocationRelativeTo(null); //centralizar a tela
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        //para ocultar a coluna ID
        tblClientes.getColumnModel().getColumn(0).setMinWidth(0);
        tblClientes.getColumnModel().getColumn(0).setMaxWidth(0);
        tblClientes.getColumnModel().getColumn(0).setWidth(0);
    }
    
    private void configurarAcoes() {

        // Botão adicionar, abre a tela de cadastro de client
        btnAdicionar.addActionListener(e -> abrirTelaAdicionar());

        // Botão de atualizar, aqui recarrega a lista de clientes
        btnAtualizar.addActionListener(e -> carregarClientes());
    
        //Botão de editar, abre a tela de edição do cliente
        btnEditar.addActionListener(e -> editarCliente());

        //Botão filtrar, e aqui aplica os filtros de nome, tipo e status
        btnFiltrar.addActionListener(e -> filtrarClientes());

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscarPorNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblTipoCliente = new javax.swing.JLabel();
        cmbTipoCliente = new javax.swing.JComboBox<>();
        lblStatusCliente = new javax.swing.JLabel();
        cmbStatusCliente = new javax.swing.JComboBox<>();
        btnFiltrar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();

        buscarPorNome.setText("Buscar por Nome");
        buscarPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPorNomeActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone", "TipoCliente", "Limite", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CLIENTES");

        lblNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNome.setText("Nome");

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        lblTipoCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTipoCliente.setText("Tipo Cliente");

        cmbTipoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALUNO", "PROFESSOR", "VISITANTE" }));
        cmbTipoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoClienteActionPerformed(evt);
            }
        });

        lblStatusCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatusCliente.setText("Status");

        cmbStatusCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATIVO", "INATIVO", "BLOQUEADO" }));
        cmbStatusCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusClienteActionPerformed(evt);
            }
        });

        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFiltrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnAdicionar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnEditar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnAtualizar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblNome)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtNome))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblTipoCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblStatusCliente)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbStatusCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoCliente)
                    .addComponent(cmbTipoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatusCliente)
                    .addComponent(cmbStatusCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionar)
                    .addComponent(btnEditar)
                    .addComponent(btnAtualizar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void abrirTelaAdicionar() {
        ClienteAdicionar tela = new ClienteAdicionar(controller);
        tela.setLocationRelativeTo(this);// pra centralizar a tela em relação à tela atual
        tela.setVisible(true);

        // quando fechar a tela, atualiza a lista
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            carregarClientes();
        }
    });
}
    
    private void filtrarClientes() {

        String nome = txtNome.getText();

        String tipo = (String) cmbTipoCliente.getSelectedItem();
        String status = (String) cmbStatusCliente.getSelectedItem(); //Obtendo o valor selecionado no ComboBox

        // faz a busca dos clientes de acordo com os filtros informados
        List<Cliente> clientes = controller.filtrar(
            nome,
            tipo,
            status
        );

        DefaultTableModel model =
            (DefaultTableModel) tblClientes.getModel();

        model.setRowCount(0); // aqui limpa a tabela antes de inserir os novos resultados

    
        // preenche a tabela com os clientes filtrados
        for (Cliente c : clientes) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNomeCompleto(),
                c.getCpf(),
                c.getTelefone(),
                c.getTipoCliente(),
                c.getLimiteEmprestimo(),
                c.getStatusPessoa()
            });
        }
    }


    // método que preenche a tabela com os dados dos clientes
    private void carregarClientes() {
        
        logger.info("Carregando lista de clientes...");// Log para depuração
        
        var clientes = controller.findAll(); //busca todos os clientes

        //aqui cria o modelo da tabela
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) tblClientes.getModel();

        model.setRowCount(0); // limpa a tabela antes

        //preenche a tabela com os dados
        for (var c : clientes) {
            model.addRow(new Object[]{
                c.getId(),
                c.getNomeCompleto(),
                c.getCpf(),
                c.getTelefone(),
                c.getTipoCliente(),
                c.getLimiteEmprestimo(),
                c.getStatusPessoa()
        });
         }
    }
    
    private void editarCliente() {

        int linha = tblClientes.getSelectedRow();  // Verifica a linha selecionada

        if (linha == -1) {
            // Caso o usuário não tenha selecionado um cliente
            JOptionPane.showMessageDialog(
                this,
                "Selecione um cliente para editar.",
                "Atenção",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Long idCliente = (Long) tblClientes.getValueAt(linha, 0); // Obtém o ID do cliente

        // Obtém o cliente pelo ID do controlador
        Cliente cliente = controller.findById(idCliente);

        // Cria a tela de edição com o cliente
        ClienteEditar telaEditar = new ClienteEditar(controller, cliente);

        // Abre a tela de edição
        telaEditar.setLocationRelativeTo(this);  // Centraliza a tela
        telaEditar.setVisible(true);

        // Atualiza a lista de clientes após fechar a tela de edição
        telaEditar.addWindowListener(new java.awt.event.WindowAdapter() {
            
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                logger.info("Cliente editado com sucesso, recarregando lista...");
                carregarClientes();  // Recarrega os clientes após a edição
            }
        });
        }


    
    private void buscarPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarPorNomeActionPerformed

    private void cmbTipoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoClienteActionPerformed

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void cmbStatusClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStatusClienteActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        carregarClientes();
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton buscarPorNome;
    private javax.swing.JComboBox<String> cmbStatusCliente;
    private javax.swing.JComboBox<String> cmbTipoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblStatusCliente;
    private javax.swing.JLabel lblTipoCliente;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
