package br.com.ifba.biblioteca.emprestimo.view;

/**
 *
 * @author guilhermeAmedrado
 */

import br.com.ifba.biblioteca.emprestimo.controller.EmprestimoIController;
import br.com.ifba.biblioteca.emprestimo.entity.Emprestimo;
import br.com.ifba.biblioteca.multa.view.MultaGerar;
import java.awt.event.KeyEvent;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.stereotype.Component;

@Component
public class EmprestimoListar extends javax.swing.JFrame {
   
// Variável para controlar o filtro da tabela
    private TableRowSorter<DefaultTableModel> sorter;

    @Autowired
    private EmprestimoIController emprestimoController;

    @Autowired
    private ApplicationContext context;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmprestimoListar.class.getName());
    
    /**
     * Creates new form EmprestimoAdicionar
     */
    
    public EmprestimoListar() {
        initComponents();
        setTitle("Gestão de Empréstimos");
        setLocationRelativeTo(null);
        configurarTabela();
        carregarDados();
    }
    
    private void configurarTabela() {
        // Define os nomes das colunas da tabela
        String[] colunas = {"ID", "Cliente", "Exemplar", "Data Emp.", "Devolução", "Status"};
        
        // Cria um modelo de tabela (onde os dados ficam guardados)
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(colunas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Isso impede que o usuário edite a célula clicando duas vezes
            }
        };
        
        // Aplica esse modelo na sua tabela visual (tblEmprestimos)
        tblEmprestimos.setModel(modelo);
        
        
        // Cria o classificador (sorter) baseado no modelo que acabamos de criar
        sorter = new javax.swing.table.TableRowSorter<>(modelo);
        
        // Avisa a tabela que ela deve usar esse classificador
        tblEmprestimos.setRowSorter(sorter);
    }
    
    
    public void carregarDados() {
        try {
            // Pega o modelo da tabela para poder mexer nele
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblEmprestimos.getModel();
            
            // Limpa as linhas antigas para não duplicar
            modelo.setRowCount(0); 

            // Busca a lista atualizada do banco usando o Controller
            java.util.List<br.com.ifba.biblioteca.emprestimo.entity.Emprestimo> lista = emprestimoController.findAll();

            // Adiciona cada empréstimo como uma nova linha na tabela
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            for (br.com.ifba.biblioteca.emprestimo.entity.Emprestimo emp : lista) {
                modelo.addRow(new Object[]{
                    emp.getId(),
                    emp.getCliente().getNomeCompleto(), // Mostra o Nome do Cliente
                    emp.getExemplar().getId(),          // Mostra o ID do Exemplar
                    emp.getDataEmprestimo() != null ? emp.getDataEmprestimo().format(formatter) : "",            // Data de quando pegou
                    emp.getDataPrevistaDevolucao() != null ? emp.getDataPrevistaDevolucao().format(formatter) : "",     // Data de quando tem que devolver
                    emp.getStatus()                     // Se está ATIVO, ATRASADO, etc
                });
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar dados: " + e.getMessage());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmprestimos = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnMultas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(tblEmprestimos);

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnMultas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMultas.setText("Multas");
        btnMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Buscar por ID:");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMultas)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAdicionar)
                        .addComponent(btnEditar)
                        .addComponent(btnExcluir)
                        .addComponent(btnMultas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
      try {  
            // Pega a tela de Adicionar que o Spring criou
            EmprestimoAdicionar telaAdicionar = context.getBean(EmprestimoAdicionar.class);
            
            // Passa a referência desta lista (para atualizar a tabela depois)
            telaAdicionar.setEmprestimoListar(this);
            
            // Configurações de exibição
            telaAdicionar.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE); // Fecha só ela, não o app todo
            telaAdicionar.setLocationRelativeTo(null); // Centraliza na tela
            
            // Mostra a janela diretamente! (Sem criar JDialog)
            telaAdicionar.setVisible(true);
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao abrir tela: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // Verifica seleção
        int linhaSelecionada = tblEmprestimos.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo para excluir/devolver!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Converte índice visual para modelo (por causa da busca/filtro)
        int linhaModelo = tblEmprestimos.convertRowIndexToModel(linhaSelecionada);
        Long id = (Long) tblEmprestimos.getModel().getValueAt(linhaModelo, 0);

        // Confirmação
        int confirmacao = JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja remover este empréstimo?\nIsso devolverá o livro ao estoque.",
                "Confirmar Exclusão",
                JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                Emprestimo remover = new Emprestimo();
                remover.setId(id);

                emprestimoController.delete(remover);

                carregarDados();
                JOptionPane.showMessageDialog(this, "Empréstimo removido com sucesso!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int linhaSelecionada = tblEmprestimos.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione um empréstimo para editar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int linhaModelo = tblEmprestimos.convertRowIndexToModel(linhaSelecionada);
        Long id = (Long) tblEmprestimos.getModel().getValueAt(linhaModelo, 0);

        try {
            Emprestimo emp = emprestimoController.findById(id);

            EmprestimoEditar editar = new EmprestimoEditar(emprestimoController, this, emp);
            editar.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao buscar dados: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String texto = txtBuscar.getText();
        if (texto.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            try {
                sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
            } catch (Exception e) {
                // Ignora erro
            }
        }
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultasActionPerformed
        //relacionamento com a tela de multas
        
         int linha = tblEmprestimos.getSelectedRow();

    if (linha == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um empréstimo.");
        return;
    }

    int linhaModelo = tblEmprestimos.convertRowIndexToModel(linha);
    Long id = (Long) tblEmprestimos.getModel().getValueAt(linhaModelo, 0);

    try {
        Emprestimo emp = emprestimoController.findById(id);

        if (emp == null) {
            JOptionPane.showMessageDialog(this, "Empréstimo não encontrado.");
            return;
        }

        // pega tela pelo Spring
        MultaGerar tela = context.getBean(MultaGerar.class);

        // ⭐ injeção correta
        tela.setEmprestimo(emp);   // ESSENCIAL
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao abrir multa: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnMultasActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EmprestimoListar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnMultas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmprestimos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
