/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.biblioteca.local.view;

import br.com.ifba.biblioteca.local.controller.LocalIController;
import br.com.ifba.biblioteca.local.entity.Local;
import javax.swing.JOptionPane;

/**
 *
 * @author jeffe
 */
public class LocalAdicionar extends javax.swing.JFrame {
    
    private LocalListar telaListar;
    private LocalIController localController;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LocalAdicionar.class.getName());

    /**
     * Creates new form LocalAdicionar
     */
    public LocalAdicionar(LocalListar telaListar, LocalIController localController) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        this.telaListar = telaListar;
        this.localController = localController;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtComplemento = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cidade:");

        jLabel2.setText("Rua:");

        jLabel3.setText("Número:");

        jLabel4.setText("Complemento:");

        btnSalvar.setText("SALVAR");

        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCidade)
                    .addComponent(txtRua)
                    .addComponent(txtNumero)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }
    
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String cidade = txtCidade.getText();
            String rua = txtRua.getText();
            String numeroStr = txtNumero.getText();
            String complemento = txtComplemento.getText();

            if (cidade == null || cidade.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe a cidade.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (rua == null || rua.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe a rua.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (numeroStr == null || numeroStr.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe o número.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int numero;
            try {
                numero = Integer.parseInt(numeroStr.trim());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Número inválido. Digite apenas números.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Local local = new Local();
            local.setCidade(cidade.trim());
            local.setRua(rua.trim());
            local.setNumero(numero);
            local.setComplemento(complemento); // pode ser vazio
            local.setAtivo(true);

            localController.save(local);

            JOptionPane.showMessageDialog(this, "Local cadastrado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            if (telaListar != null) {
                telaListar.atualizarLista();
            }

            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Erro ao cadastrar", JOptionPane.ERROR_MESSAGE);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
