/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.biblioteca.reserva.view;

import br.com.ifba.biblioteca.reserva.entity.Reserva;
import br.com.ifba.biblioteca.reserva.entity.StatusReserva;
import br.com.ifba.biblioteca.reserva.service.ReservaService;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

/**
 *
 * @author misae
 */

//Tela responsável por listar, filtrar e gerenciar reservas.

@Component // Define a classe como um Bean gerenciado pelo Spring
@Scope("prototype") // Cada chamada cria uma nova instância da tela
public class ReservaListar extends javax.swing.JFrame {
    
    // Logger para registro de eventos da aplicação
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReservaListar.class.getName());

    // Serviço responsável pelas regras de negócio de Reserva
    @Autowired
    private ReservaService reservaService;
    
    // Contexto do Spring usado para obter outras telas como Beans
    @Autowired
    private ApplicationContext context;

    // Lista usada para mapear a linha da tabela com o objeto Reserva
    private List<Reserva> reservasExibidas;

    
    /**
     * Creates new form ReservaListar
     */
    
    //Construtor da tela.
    public ReservaListar() {
        initComponents();// Inicializa os componentes da interface
        setLocationRelativeTo(null); // centraliza
        preencherComboStatus(); // Preenche o ComboBox com os status possíveis
        
    }
    
    
    //Preenche a tabela de reservas
    public void carregarTabela(List<Reserva> reservas) {
        String[] colunas = {"Cliente", "Exemplar", "Data", "Status"};
        javax.swing.table.DefaultTableModel modelo =
                new javax.swing.table.DefaultTableModel(colunas, 0);

        for (Reserva r : reservas) {
            Object[] linha = {
                r.getCliente().getId(),
                r.getExemplar().getNumeroTombamento(),
                r.getDataReserva(),
                r.getStatus()
            };
            modelo.addRow(linha);
        }

        tblReservas.setModel(modelo); 
        this.reservasExibidas = reservas; // Guarda a lista exibida para ações futuras
    }
    
    public void carregarDados() {
        carregarTabela(reservaService.findAll());
    }
    
    //Preenche o combo de status a partir do enum StatusReserva
    private void preencherComboStatus() {
        cbStatus.removeAllItems();
        for (StatusReserva status : StatusReserva.values()) {
            cbStatus.addItem(status.name());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProcurar = new javax.swing.JTextField();
        txtProcurar1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();
        btnAdicionar = new javax.swing.JButton();
        btnAtender = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        cbStatus = new javax.swing.JComboBox<>();
        lblClienteId = new javax.swing.JLabel();
        txtClienteId = new javax.swing.JTextField();
        lblExemplarId = new javax.swing.JLabel();
        txtExemplarId = new javax.swing.JTextField();
        btnFiltrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();

        txtProcurar.setBackground(new java.awt.Color(255, 255, 255));
        txtProcurar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProcurar.setForeground(new java.awt.Color(80, 80, 80));
        txtProcurar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProcurar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));
        txtProcurar.setOpaque(true);
        txtProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurarActionPerformed(evt);
            }
        });

        txtProcurar1.setBackground(new java.awt.Color(255, 255, 255));
        txtProcurar1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtProcurar1.setForeground(new java.awt.Color(80, 80, 80));
        txtProcurar1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProcurar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(180, 180, 180), 1, true));
        txtProcurar1.setOpaque(true);
        txtProcurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProcurar1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Exemplar", "Data", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblReservas);

        btnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        btnAtender.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtender.setText("Atender");
        btnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtenderActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("RESERVAS");

        lblStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStatus.setText("Status:");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PENDENTE", "ATENDIDA", "CANCELADA", " " }));
        cbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusActionPerformed(evt);
            }
        });

        lblClienteId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblClienteId.setText("Cliente ID:");

        lblExemplarId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblExemplarId.setText("Exemplar Tombamento:");

        txtExemplarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExemplarIdActionPerformed(evt);
            }
        });

        btnFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        btnAtualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFiltrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblExemplarId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtExemplarId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnAdicionar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAtender)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnCancelar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAtualizar))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblClienteId)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtClienteId))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblStatus)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteId)
                    .addComponent(txtClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExemplarId)
                    .addComponent(txtExemplarId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtender, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtProcurarActionPerformed

    private void txtProcurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProcurar1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtProcurar1ActionPerformed

    //Abre a tela de cadastro de reserva.
    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // Obtém a tela ReservaAdicionar como Bean do Spring
        ReservaAdicionar tela = context.getBean(ReservaAdicionar.class);
        tela.setTelaPai(this); // Define esta tela como tela pai
        tela.setVisible(true);

    }//GEN-LAST:event_btnAdicionarActionPerformed

    //Abre a tela de atendimento da reserva selecionada.
    private void btnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtenderActionPerformed
        int linha = tblReservas.getSelectedRow();

        if (linha != -1) {
            // Recupera a reserva correspondente à linha selecionada
            Reserva reserva = reservasExibidas.get(linha);
            ReservaAtender tela = new ReservaAtender(reserva, reservaService);

            // Atualiza a tabela quando a tela fechar
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    carregarTabela(reservaService.findAll());
                }
            });

            tela.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione uma reserva para atender.");
        }
    }//GEN-LAST:event_btnAtenderActionPerformed

    private void cbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusActionPerformed

    //Aplica filtros por status, cliente e exemplar.
    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        List<Reserva> filtradas = reservaService.findAll();

        // Filtro por status
        String statusSelecionado = (String) cbStatus.getSelectedItem();
        if (statusSelecionado != null && !statusSelecionado.isBlank()) {
            filtradas = filtradas.stream()
                    .filter(r -> r.getStatus().name().equals(statusSelecionado))
                    .toList();
        }

        // Filtro por Cliente ID
        if (!txtClienteId.getText().isBlank()) {
            try {
                long clienteId = Long.parseLong(txtClienteId.getText());
                filtradas = filtradas.stream()
                        .filter(r -> r.getCliente().getId() == clienteId)
                        .toList();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Cliente ID deve ser numérico!",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        // Filtro por Exemplar (numero de tombamento)
        if (!txtExemplarId.getText().isBlank()) {
            try {
                long exemplarId = Long.parseLong(txtExemplarId.getText());
                filtradas = filtradas.stream()
                        .filter(r -> r.getExemplar().getNumeroTombamento() == exemplarId)
                        .toList();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this,
                        "Exemplar ID deve ser numérico!",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }
        }

        carregarTabela(filtradas);
    }//GEN-LAST:event_btnFiltrarActionPerformed

    //Recarrega todas as reservas na tabela.
    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        carregarTabela(reservaService.findAll());
        JOptionPane.showMessageDialog(this, "Tabela atualizada!");
    }//GEN-LAST:event_btnAtualizarActionPerformed

    //Cancela a reserva selecionada.
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       int linha = tblReservas.getSelectedRow();

    if (linha != -1) {
        Reserva reserva = reservasExibidas.get(linha); // pega a reserva selecionada

        // Verifica se já está cancelada
        if (reserva.getStatus() == StatusReserva.CANCELADA) {
            JOptionPane.showMessageDialog(
                this,
                "Esta reserva já está cancelada!",
                "Aviso",
                JOptionPane.WARNING_MESSAGE
            );
            return; // Sai do método
        }

        int opcao = JOptionPane.showConfirmDialog(
                this,
                "Deseja realmente cancelar esta reserva?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION
        );

        if (opcao == JOptionPane.YES_OPTION) {
            reservaService.delete(reserva); // Remove a reserva
            carregarTabela(reservaService.findAll());
            JOptionPane.showMessageDialog(this, "Reserva cancelada!");
        }
    } else {
        JOptionPane.showMessageDialog(this,
                "Selecione uma reserva para cancelar.",
                "Aviso",
                JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnCancelarActionPerformed
    
        
    private void txtExemplarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExemplarIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExemplarIdActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtender;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClienteId;
    private javax.swing.JLabel lblExemplarId;
    private javax.swing.JLabel lblStatus;
    public javax.swing.JTable tblReservas;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtExemplarId;
    private javax.swing.JTextField txtProcurar;
    private javax.swing.JTextField txtProcurar1;
    // End of variables declaration//GEN-END:variables
}
