/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.biblioteca.reserva.view;

import br.com.ifba.biblioteca.exemplar.entity.Exemplar;
import br.com.ifba.biblioteca.reserva.entity.Reserva;
import br.com.ifba.biblioteca.reserva.entity.StatusReserva;
import br.com.ifba.biblioteca.reserva.service.ReservaService;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;
import br.com.ifba.biblioteca.cliente.entity.Cliente;
import br.com.ifba.biblioteca.cliente.service.ClienteService;



/**
 *
 * @author misae
 */

/*Tela responsável pela criação de uma nova Reserva.
  Permite selecionar um Cliente
  e um Exemplar existente para efetivar a reserva.*/
@Component
@Scope("prototype")
public class ReservaAdicionar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(ReservaAdicionar.class.getName());

    
    // Serviço responsável pelas regras de negócio da Reserva
    @Autowired
    private ReservaService reservaService;
    
    //serviço responsável pelas regras de negócio de Cliente
    @Autowired
    private ClienteService clienteService;
    
    

    // Contexto Spring usado para criar telas gerenciadas (@Component)
    @Autowired
    private ApplicationContext context;

    // Cliente selecionado
    private Cliente clienteSelecionado;

    // Exemplar selecionado
    private Exemplar exemplarSelecionado;

    // Tela pai responável pela listagem de reservas
    private ReservaListar telaPai;


    //Construtor da tela de criação de reserva.
    @Autowired
    public ReservaAdicionar() {
        initComponents();
        setLocationRelativeTo(null); // centraliza
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        // Deixa os campos de cliente e exemplar não editáveis manualmente
        txtClienteId.setEditable(false);
        txtTombamento.setEditable(false); 
        

        // Configuração do spinner de data
        spinnerDataReserva.setModel(new SpinnerDateModel());
        JSpinner.DateEditor editor =
                new JSpinner.DateEditor(spinnerDataReserva, "dd/MM/yyyy");
        spinnerDataReserva.setEditor(editor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtClienteId = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnBuscarExemplar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        spinnerDataReserva = new javax.swing.JSpinner();
        txtTombamento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CRIAR RESERVA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Cliente");

        btnBuscarCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarCliente.setText("Buscar Cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Exemplar");

        btnBuscarExemplar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBuscarExemplar.setText("Buscar Exemplar");
        btnBuscarExemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarExemplarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Data da Reserva");

        btnSalvar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSalvar)
                        .addGap(54, 54, 54)
                        .addComponent(btnCancelar)
                        .addGap(113, 113, 113))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerDataReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCliente)
                                .addGap(156, 156, 156))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTombamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarExemplar)
                                .addGap(143, 143, 143))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClienteId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(btnBuscarExemplar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTombamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spinnerDataReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTelaPai(ReservaListar telaPai) {
        this.telaPai = telaPai;
    }

    
    //Recebe o ID do cliente selecionado
    public void setClienteSelecionado(Cliente cliente) {
        this.clienteSelecionado = cliente;
        txtClienteId.setText(String.valueOf(cliente.getId()));
    }

    
    // Recebe o exemplar selecionado na tela Buscar Exemplar
    public void setExemplarSelecionado(Exemplar exemplar) {
        this.exemplarSelecionado = exemplar;
        txtTombamento.setText(String.valueOf(exemplar.getNumeroTombamento()));
    }

    
    // Abre a tela de busca de cliente (dados fictícios para testes)
    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // Tela de cliente ainda em desenvolvimento por outro integrante
        BuscarCliente tela = context.getBean(BuscarCliente.class);
        tela.setTelaPai(this);
        tela.setVisible(true);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    // Abre a tela de busca de exemplar utilizando o contexto Spring
    private void btnBuscarExemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarExemplarActionPerformed
        BuscarExemplar tela = context.getBean(BuscarExemplar.class);
        
        tela.setTelaPai(this);
        tela.carregarExemplares();
        tela.setVisible(true);
    }//GEN-LAST:event_btnBuscarExemplarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose(); // fecha a tela sem salvar
    }//GEN-LAST:event_btnCancelarActionPerformed

    
    // Realiza a validação dos dados e cria uma nova reserva
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
            
        // Validações básicas de negócio
        try {
            logger.info("Iniciando criação de reserva");

            if (clienteSelecionado == null) {
                throw new RuntimeException("Selecione um cliente!");
            }

            if (exemplarSelecionado == null) {
                throw new RuntimeException("Selecione um exemplar!");
            }

            Reserva reserva = new Reserva();

            //Cliente selecionado
            reserva.setCliente(clienteSelecionado);

            reserva.setExemplar(exemplarSelecionado);

            // Data escolhida pelo usuário
            Date data = (Date) spinnerDataReserva.getValue();
            reserva.setDataReserva(
                    data.toInstant()
                            .atZone(ZoneId.systemDefault())
                            .toLocalDate()
            );

            reserva.setStatus(StatusReserva.PENDENTE);

            // Persiste a reserva no sistema
            reservaService.save(reserva);

            if (telaPai != null) {
                telaPai.carregarTabela(reservaService.findAll());
            }

            JOptionPane.showMessageDialog(this, "Reserva criada com sucesso!");
            logger.info("Reserva criada com sucesso");
            this.dispose();

        } catch (RuntimeException e) {
            logger.severe("Erro ao criar reserva: " + e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarExemplar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spinnerDataReserva;
    private javax.swing.JTextField txtClienteId;
    private javax.swing.JTextField txtTombamento;
    // End of variables declaration//GEN-END:variables
}
